### ISSUE TITLE
Limit of 500 records preventing accurate comparison

### ISSUE THREAD

**Issue by htkalez** [riklewis/comparetheproject#1]
The limit of 500 records means I can't compare two xpcs effectively. The files are truncated to 500 and (both xpcs have over 4000 records) and the ordering of the items within the two xpcs is not the same. 
I'm using this for a real piece of work  - I'm working on the re-import of an admissions template for GCU - we've done a lot of prep work comparing the comparing the existing files against the latest template, but there could be gaps - this facility seems like a great option to compare the two in a more systematic way. 
Can the record limit be substantially increased?

**Comment by riklewis** [comment]
I've upped the limit for you 😊
