### ISSUE TITLE
Possiblity of downloading and saving report

### ISSUE THREAD

**Issue by htkalez** [riklewis/comparetheproject#2]
Feature request - would be really useful to be able to save the results. In my test example, with the volume of data I'm looking at comparing it might not be possible within one session, so would be good to be able to export/download the results.

**Comment by riklewis** [comment]
Interesting idea.  What sort of format were you thinking (eg. PDF/CSV)?

Would you expect this export/download to just include the record comparison, or also all of the field comparisons that you can drill down into by clicking on a record?

**Comment by htkalez** [comment]
I can see myself using two levels of detail here - one, a high level list of the items with the percentage difference/new/no-change data. That would be adequately held in a csv. This would require me to go back into the records and work out where the differences are again, but as a basic option definitely workable. 
The drill-down expanded comparison between the records is the really useful part of this, but that would be hard to represent in a spreadsheet - especially for large files. PDF could represent that level of detail, - and if you were thinking of ultimately providing this somehow to customers then I can see IT departments/project teams using PDFs of comparisons for CAB type processes. Visually its very easy to see the differences/similarities in the web view now, so preserving that in a PDF download I can see being useful.

My ideal enhancement (and I'm not suggesting this is feasible) would be to be able to save and return to the comparison - rather than having to export the data, just to be able to return to the comparison at a later date (maybe time limited?).  I imagine that changes the nature of the development and requires a lot more resource to start storing users'  comparisons.

**Comment by riklewis** [comment]
1. It should be possible to add an "Export to CSV" link into the summary section which exports the record comparison.

2. I agree that the field level comparison won't practical to do in a spreadsheet, but like the idea of PDF output.  At the least, it could create a print view that could then be printed to a PDF using Windows in-built PDF printer.  The difficulty is that it might take a long time (several minutes) to generate this view, as it would need to loop through each record/pair and generate the comparison for it, which with the size of files we talked about on #1 would be a lot.

3. Allowing users to create accounts to store files and comparisons has been in the back of my mind. In fact I originally thought I might set a lower limit for "guest" users and then allow signed in users to have higher limits (see #1), but it certainly would be a lot more work.

**Comment by riklewis** [comment]
I've just released a new version with 1 and 2 both added.  

3 is not going to happen just yet, but perhaps in the future :)

Closing this issue now.
